### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by alce65** [cristian-tonato/202210w3-ch5-cristian-Tonato#1]
Hola Cristian.
El commit inicial no debe incluir  un readme sin contenido o sin sentido.
Tiene que incluir UN CONTENIDO VÁLIDO: al menos las instrucciones para hacer el challenge.
Esto YA lo deberías tener desde el principio.

**Comment by cristian-tonato** [comment]
Hola Alejandro. Pensé que lo tenia con las intrucciones con el challenge. No volverá a pasar.

**Comment by alce65** [comment]
No hay problema. Cierro el issue
