### ISSUE TITLE
Work in progress

### ISSUE THREAD

**Issue by alce65** [cristian-tonato/202210w3-ch5-cristian-Tonato#2]
Hola Cristian
No has subido nada después del "Initial commit".
Si has podido hacer algo, recuerda que la rama con la feature en l que estemos trabajando  se sube a remoto en cuanto tiene algún contenido. No hay que esperar a que este lista para la PR. De esta forma estamos salvaguardando nuestro trabajo en Github, por si acaso pasara algo en local

**Comment by cristian-tonato** [comment]
Hecho!

**Comment by alce65** [comment]
Ok. Cierro el issue
